client_max_body_size 500M;

# your vpc subnet where ELB resides in
set_real_ip_from  10.0.0.0/8;

# AWS CloudFront IP/CIDR range http://d7uri8nf7uskq.cloudfront.net/tools/list-cloudfront-ips
set_real_ip_from 120.52.22.96/27;
set_real_ip_from 205.251.249.0/24;
set_real_ip_from 180.163.57.128/26;
set_real_ip_from 204.246.168.0/22;
set_real_ip_from 18.160.0.0/15;
set_real_ip_from 205.251.252.0/23;
set_real_ip_from 54.192.0.0/16;
set_real_ip_from 204.246.173.0/24;
set_real_ip_from 54.230.200.0/21;
set_real_ip_from 120.253.240.192/26;
set_real_ip_from 116.129.226.128/26;
set_real_ip_from 130.176.0.0/17;
set_real_ip_from 108.156.0.0/14;
set_real_ip_from 99.86.0.0/16;
set_real_ip_from 205.251.200.0/21;
set_real_ip_from 223.71.71.128/25;
set_real_ip_from 13.32.0.0/15;
set_real_ip_from 120.253.245.128/26;
set_real_ip_from 13.224.0.0/14;
set_real_ip_from 70.132.0.0/18;
set_real_ip_from 15.158.0.0/16;
set_real_ip_from 13.249.0.0/16;
set_real_ip_from 18.238.0.0/15;
set_real_ip_from 18.244.0.0/15;
set_real_ip_from 205.251.208.0/20;
set_real_ip_from 65.9.128.0/18;
set_real_ip_from 130.176.128.0/18;
set_real_ip_from 58.254.138.0/25;
set_real_ip_from 54.230.208.0/20;
set_real_ip_from 116.129.226.0/25;
set_real_ip_from 52.222.128.0/17;
set_real_ip_from 18.164.0.0/15;
set_real_ip_from 64.252.128.0/18;
set_real_ip_from 205.251.254.0/24;
set_real_ip_from 54.230.224.0/19;
set_real_ip_from 71.152.0.0/17;
set_real_ip_from 216.137.32.0/19;
set_real_ip_from 204.246.172.0/24;
set_real_ip_from 18.172.0.0/15;
set_real_ip_from 120.52.39.128/27;
set_real_ip_from 118.193.97.64/26;
set_real_ip_from 223.71.71.96/27;
set_real_ip_from 18.154.0.0/15;
set_real_ip_from 54.240.128.0/18;
set_real_ip_from 205.251.250.0/23;
set_real_ip_from 180.163.57.0/25;
set_real_ip_from 52.46.0.0/18;
set_real_ip_from 223.71.11.0/27;
set_real_ip_from 52.82.128.0/19;
set_real_ip_from 54.230.0.0/17;
set_real_ip_from 54.230.128.0/18;
set_real_ip_from 54.239.128.0/18;
set_real_ip_from 130.176.224.0/20;
set_real_ip_from 36.103.232.128/26;
set_real_ip_from 52.84.0.0/15;
set_real_ip_from 143.204.0.0/16;
set_real_ip_from 144.220.0.0/16;
set_real_ip_from 120.52.153.192/26;
set_real_ip_from 119.147.182.0/25;
set_real_ip_from 120.232.236.0/25;
set_real_ip_from 54.182.0.0/16;
set_real_ip_from 58.254.138.128/26;
set_real_ip_from 120.253.245.192/27;
set_real_ip_from 54.239.192.0/19;
set_real_ip_from 18.64.0.0/14;
set_real_ip_from 120.52.12.64/26;
set_real_ip_from 99.84.0.0/16;
set_real_ip_from 130.176.192.0/19;
set_real_ip_from 52.124.128.0/17;
set_real_ip_from 204.246.164.0/22;
set_real_ip_from 13.35.0.0/16;
set_real_ip_from 204.246.174.0/23;
set_real_ip_from 36.103.232.0/25;
set_real_ip_from 119.147.182.128/26;
set_real_ip_from 118.193.97.128/25;
set_real_ip_from 120.232.236.128/26;
set_real_ip_from 204.246.176.0/20;
set_real_ip_from 65.8.0.0/16;
set_real_ip_from 65.9.0.0/17;
set_real_ip_from 108.138.0.0/15;
set_real_ip_from 120.253.241.160/27;

# always put the following 2 lines in the bottom of ip list
real_ip_header X-Forwarded-For;
real_ip_recursive on;

server_tokens off;
fastcgi_hide_header X-Powered-By;
fastcgi_hide_header X-Pingback;

charset utf8;

gzip                on;
gzip_vary           on;
gzip_proxied        any;
gzip_types          *;

index index.php;

location  ~ ~$              { return 404; }
location  = /wp/xmlrpc.php  { return 404; }
location  = /wp/readme.html { return 404; }
location ^~ /app/uploads    { }
# heroku-buildpack-php defines "location ~ \.php" rule for fcgi

set $expires 360;
if ($args) { set $expires max; }

location / {
    expires $expires;
    add_header Cache-Control "public";
    try_files $uri $uri/ /index.php?$args;
    if ($args ~ "^author=\d") { return 301 /; }
}

add_header "X-UA-Compatible" "IE=Edge,chrome=1";

# Needed by multi site
rewrite ^/(wp-.*.php)$ /wp/$1 last;
rewrite ^/(wp-(content|admin|includes).*) /wp/$1 last;

